package cpanvote::Model::cpanvoteDB;

use strict;
use base 'Catalyst::Model::DBIC::Schema';

__PACKAGE__->config(
    schema_class => 'cpanvote::Schema',
    
    connect_info => {
        dsn => 'dbi:SQLite:dbname=/home/yanick/work/perl-modules/cpanvote/db.sqlite',
        user => '',
        password => '',
    }
);

=head1 NAME

cpanvote::Model::cpanvoteDB - Catalyst DBIC Schema Model

=head1 SYNOPSIS

See L<cpanvote>

=head1 DESCRIPTION

L<Catalyst::Model::DBIC::Schema> Model using schema L<cpanvote::Schema>

=head1 GENERATED BY

Catalyst::Helper::Model::DBIC::Schema - 0.4

=head1 AUTHOR

Yanick Champoux

=head1 LICENSE

This library is free software, you can redistribute it and/or modify
it under the same terms as Perl itself.

=cut

1;
