---
schema:
  procedures: {}
  tables:
    dbix_class_deploymenthandler_versions:
      constraints:
        - deferrable: 1
          expression: ''
          fields:
            - id
          match_type: ''
          name: ''
          on_delete: ''
          on_update: ''
          options: []
          reference_fields: []
          reference_table: ''
          type: PRIMARY KEY
        - deferrable: 1
          expression: ''
          fields:
            - version
          match_type: ''
          name: dbix_class_deploymenthandler_versions_version
          on_delete: ''
          on_update: ''
          options: []
          reference_fields: []
          reference_table: ''
          type: UNIQUE
      fields:
        ddl:
          data_type: text
          default_value: ~
          is_nullable: 1
          is_primary_key: 0
          is_unique: 0
          name: ddl
          order: 3
          size:
            - 0
        id:
          data_type: int
          default_value: ~
          is_auto_increment: 1
          is_nullable: 0
          is_primary_key: 1
          is_unique: 0
          name: id
          order: 1
          size:
            - 0
        upgrade_sql:
          data_type: text
          default_value: ~
          is_nullable: 1
          is_primary_key: 0
          is_unique: 0
          name: upgrade_sql
          order: 4
          size:
            - 0
        version:
          data_type: varchar
          default_value: ~
          is_nullable: 0
          is_primary_key: 0
          is_unique: 1
          name: version
          order: 2
          size:
            - 50
      indices: []
      name: dbix_class_deploymenthandler_versions
      options: []
      order: 1
  triggers: {}
  views: {}
translator:
  add_drop_table: 0
  filename: ~
  no_comments: 0
  parser_args:
    package: &1 !!perl/hash:cpanvote::Schema
      class_mappings:
        DBIx::Class::DeploymentHandler::VersionStorage::Standard::VersionResult: __VERSION
        cpanvote::Schema::Result::Auth: Auth
        cpanvote::Schema::Result::Distributions: Distributions
        cpanvote::Schema::Result::Sessions: Sessions
        cpanvote::Schema::Result::TagDist: TagDist
        cpanvote::Schema::Result::Tags: Tags
        cpanvote::Schema::Result::Users: Users
        cpanvote::Schema::Result::Votes: Votes
      source_registrations:
        Auth: !!perl/hash:DBIx::Class::ResultSource::Table
          _columns:
            credential:
              data_type: varchar
              is_nullable: 0
              size: 20
            protocol:
              data_type: varchar
              is_nullable: 0
              size: 10
            user_id:
              data_type: integer
              is_nullable: 1
          _columns_info_loaded: 0
          _ordered_columns:
            - user_id
            - protocol
            - credential
          _primaries: &2
            - protocol
            - credential
          _relationships:
            user:
              attrs:
                accessor: single
                is_foreign_key_constraint: 1
                undef_on_null_fk: 1
              class: cpanvote::Schema::Result::Users
              cond:
                foreign.id: self.user_id
              source: cpanvote::Schema::Result::Users
          _unique_constraints:
            primary: *2
          name: Auth
          result_class: cpanvote::Schema::Result::Auth
          resultset_attributes: {}
          resultset_class: DBIx::Class::ResultSet
          schema: *1
          source_name: Auth
          sqlt_deploy_callback: default_sqlt_deploy_hook
        Distributions: !!perl/hash:DBIx::Class::ResultSource::Table
          _columns:
            distname:
              data_type: varchar
              is_nullable: 0
              size: 30
            foo:
              data_type: varchar
              is_nullable: 1
              size: 30
            id:
              data_type: integer
              is_auto_increment: 1
          _columns_info_loaded: 0
          _ordered_columns:
            - id
            - distname
            - foo
          _primaries: &3
            - id
          _relationships:
            disttags:
              attrs:
                accessor: multi
                cascade_copy: 1
                cascade_delete: 1
                join_type: LEFT
              class: cpanvote::Schema::Result::TagDist
              cond:
                foreign.dist_id: self.id
              source: cpanvote::Schema::Result::TagDist
            votes:
              attrs:
                accessor: multi
                cascade_copy: 1
                cascade_delete: 1
                join_type: LEFT
              class: cpanvote::Schema::Result::Votes
              cond:
                foreign.dist_id: self.id
              source: cpanvote::Schema::Result::Votes
          _unique_constraints:
            primary: *3
            unique_distname:
              - distname
          name: Distributions
          result_class: cpanvote::Schema::Result::Distributions
          resultset_attributes: {}
          resultset_class: DBIx::Class::ResultSet
          schema: *1
          source_name: Distributions
          sqlt_deploy_callback: default_sqlt_deploy_hook
        Sessions: !!perl/hash:DBIx::Class::ResultSource::Table
          _columns:
            expires:
              data_type: integer
              is_nullable: 1
            id:
              data_type: varchar
              is_nullable: 0
              size: 72
            session_data:
              data_type: text
              is_nullable: 1
          _columns_info_loaded: 0
          _ordered_columns:
            - id
            - session_data
            - expires
          _primaries: &4
            - id
          _relationships: {}
          _unique_constraints:
            primary: *4
          name: Sessions
          result_class: cpanvote::Schema::Result::Sessions
          resultset_attributes: {}
          resultset_class: DBIx::Class::ResultSet
          schema: *1
          source_name: Sessions
          sqlt_deploy_callback: default_sqlt_deploy_hook
        TagDist: !!perl/hash:DBIx::Class::ResultSource::Table
          _columns:
            dist_id:
              data_type: integer
            tag_id:
              data_type: integer
          _columns_info_loaded: 0
          _ordered_columns:
            - tag_id
            - dist_id
          _primaries: &5
            - tag_id
            - dist_id
          _relationships:
            dist:
              attrs:
                accessor: single
                is_foreign_key_constraint: 1
                undef_on_null_fk: 1
              class: cpanvote::Schema::Result::Distributions
              cond:
                foreign.id: self.dist_id
              source: cpanvote::Schema::Result::Distributions
            tag:
              attrs:
                accessor: single
                is_foreign_key_constraint: 1
                undef_on_null_fk: 1
              class: cpanvote::Schema::Result::Tags
              cond:
                foreign.id: self.tag_id
              source: cpanvote::Schema::Result::Tags
          _unique_constraints:
            primary: *5
          name: TagDist
          result_class: cpanvote::Schema::Result::TagDist
          resultset_attributes: {}
          resultset_class: DBIx::Class::ResultSet
          schema: *1
          source_name: TagDist
          sqlt_deploy_callback: default_sqlt_deploy_hook
        Tags: !!perl/hash:DBIx::Class::ResultSource::Table
          _columns:
            id:
              data_type: integer
              is_auto_increment: 1
            name:
              data_type: varchar
              size: 20
            user_id:
              data_type: integer
              is_nullable: 1
          _columns_info_loaded: 0
          _ordered_columns:
            - id
            - user_id
            - name
          _primaries: &6
            - id
          _relationships:
            disttags:
              attrs:
                accessor: multi
                cascade_copy: 1
                cascade_delete: 1
                join_type: LEFT
              class: cpanvote::Schema::Result::TagDist
              cond:
                foreign.tag_id: self.id
              source: cpanvote::Schema::Result::TagDist
            user:
              attrs:
                accessor: single
                is_foreign_key_constraint: 1
                undef_on_null_fk: 1
              class: cpanvote::Schema::Result::Users
              cond:
                foreign.id: self.user_id
              source: cpanvote::Schema::Result::Users
          _unique_constraints:
            primary: *6
            unique_row:
              - user_id
              - name
          name: Tags
          result_class: cpanvote::Schema::Result::Tags
          resultset_attributes: {}
          resultset_class: DBIx::Class::ResultSet
          schema: *1
          source_name: Tags
          sqlt_deploy_callback: default_sqlt_deploy_hook
        Users: !!perl/hash:DBIx::Class::ResultSource::Table
          _columns:
            id:
              data_type: integer
              is_auto_increment: 1
            username:
              data_type: varchar
              is_nullable: 0
              size: 20
          _columns_info_loaded: 0
          _ordered_columns:
            - id
            - username
          _primaries: &7
            - id
          _relationships:
            votes:
              attrs:
                accessor: multi
                cascade_copy: 1
                cascade_delete: 1
                join_type: LEFT
              class: cpanvote::Schema::Result::Votes
              cond:
                foreign.user_id: self.id
              source: cpanvote::Schema::Result::Votes
          _unique_constraints:
            primary: *7
            unique_username:
              - username
          name: Users
          result_class: cpanvote::Schema::Result::Users
          resultset_attributes: {}
          resultset_class: DBIx::Class::ResultSet
          schema: *1
          source_name: Users
          sqlt_deploy_callback: default_sqlt_deploy_hook
        Votes: !!perl/hash:DBIx::Class::ResultSource::Table
          _columns:
            comment:
              data_type: varchar
              is_nullable: 1
              size: 140
            dist_id:
              data_type: integer
            instead_id:
              data_type: integer
              is_nullable: 1
            user_id:
              data_type: integer
            vote:
              data_type: integer
              is_nullable: 1
          _columns_info_loaded: 0
          _ordered_columns:
            - user_id
            - dist_id
            - vote
            - comment
            - instead_id
          _primaries: &8
            - user_id
            - dist_id
          _relationships:
            dist:
              attrs:
                accessor: single
                is_foreign_key_constraint: 1
                undef_on_null_fk: 1
              class: cpanvote::Schema::Result::Distributions
              cond:
                foreign.id: self.dist_id
              source: cpanvote::Schema::Result::Distributions
            instead:
              attrs:
                accessor: single
                is_foreign_key_constraint: 1
                undef_on_null_fk: 1
              class: cpanvote::Schema::Result::Distributions
              cond:
                foreign.id: self.instead_id
              source: cpanvote::Schema::Result::Distributions
            user:
              attrs:
                accessor: single
                is_foreign_key_constraint: 1
                undef_on_null_fk: 1
              class: cpanvote::Schema::Result::Users
              cond:
                foreign.id: self.user_id
              source: cpanvote::Schema::Result::Users
          _unique_constraints:
            primary: *8
          name: Votes
          result_class: cpanvote::Schema::Result::Votes
          resultset_attributes: {}
          resultset_class: DBIx::Class::ResultSet
          schema: *1
          source_name: Votes
          sqlt_deploy_callback: default_sqlt_deploy_hook
        __VERSION: !!perl/hash:DBIx::Class::ResultSource::Table
          _columns:
            ddl:
              data_type: text
              is_nullable: 1
            id:
              data_type: int
              is_auto_increment: 1
            upgrade_sql:
              data_type: text
              is_nullable: 1
            version:
              data_type: varchar
              size: 50
          _columns_info_loaded: 0
          _ordered_columns:
            - id
            - version
            - ddl
            - upgrade_sql
          _primaries: &9
            - id
          _relationships: {}
          _unique_constraints:
            dbix_class_deploymenthandler_versions_version:
              - version
            primary: *9
          name: dbix_class_deploymenthandler_versions
          result_class: DBIx::Class::DeploymentHandler::VersionStorage::Standard::VersionResult
          resultset_attributes: {}
          resultset_class: DBIx::Class::DeploymentHandler::VersionStorage::Standard::VersionResultSet
          schema: *1
          source_name: __VERSION
          sqlt_deploy_callback: default_sqlt_deploy_hook
      storage: !!perl/hash:DBIx::Class::Storage::DBI
        _connect_info:
          - dbi:SQLite:mydb.sql
        _dbh_details: {}
        _dbh_gen: 0
        _dbi_connect_info:
          - dbi:SQLite:mydb.sql
          - ~
          - ~
          - &10
            AutoCommit: 1
            PrintError: 0
            RaiseError: 1
        _dbic_connect_attributes: *10
        _in_dbh_do: 0
        _sql_maker: ~
        _sql_maker_opts: {}
        debugobj: !!perl/hash:DBIx::Class::Storage::Statistics {}
        savepoints: []
        schema: *1
        transaction_depth: 0
    sources:
      - __VERSION
  parser_type: SQL::Translator::Parser::DBIx::Class
  producer_args: {}
  producer_type: SQL::Translator::Producer::YAML
  show_warnings: 0
  trace: 0
  version: 0.11006
